//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	analysisv1alpha1 "github.com/gocrane/api/analysis/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceAction) DeepCopyInto(out *AvoidanceAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceAction.
func (in *AvoidanceAction) DeepCopy() *AvoidanceAction {
	if in == nil {
		return nil
	}
	out := new(AvoidanceAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvoidanceAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceActionList) DeepCopyInto(out *AvoidanceActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvoidanceAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceActionList.
func (in *AvoidanceActionList) DeepCopy() *AvoidanceActionList {
	if in == nil {
		return nil
	}
	out := new(AvoidanceActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvoidanceActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceActionSpec) DeepCopyInto(out *AvoidanceActionSpec) {
	*out = *in
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(ThrottleAction)
		**out = **in
	}
	if in.Eviction != nil {
		in, out := &in.Eviction, &out.Eviction
		*out = new(EvictionAction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceActionSpec.
func (in *AvoidanceActionSpec) DeepCopy() *AvoidanceActionSpec {
	if in == nil {
		return nil
	}
	out := new(AvoidanceActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceActionStatus) DeepCopyInto(out *AvoidanceActionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceActionStatus.
func (in *AvoidanceActionStatus) DeepCopy() *AvoidanceActionStatus {
	if in == nil {
		return nil
	}
	out := new(AvoidanceActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvoidanceStrategy) DeepCopyInto(out *AvoidanceStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvoidanceStrategy.
func (in *AvoidanceStrategy) DeepCopy() *AvoidanceStrategy {
	if in == nil {
		return nil
	}
	out := new(AvoidanceStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUBurstCfg) DeepCopyInto(out *CPUBurstCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUBurstCfg.
func (in *CPUBurstCfg) DeepCopy() *CPUBurstCfg {
	if in == nil {
		return nil
	}
	out := new(CPUBurstCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUQOSCfg) DeepCopyInto(out *CPUQOSCfg) {
	*out = *in
	if in.CPUPriority != nil {
		in, out := &in.CPUPriority, &out.CPUPriority
		*out = new(int32)
		**out = **in
	}
	if in.ContainerPriority != nil {
		in, out := &in.ContainerPriority, &out.ContainerPriority
		*out = new(int32)
		**out = **in
	}
	out.CPUBurstCfg = in.CPUBurstCfg
	out.HtIsolateCfg = in.HtIsolateCfg
	out.CPUSetPolicyCfg = in.CPUSetPolicyCfg
	out.RDTCfg = in.RDTCfg
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUQOSCfg.
func (in *CPUQOSCfg) DeepCopy() *CPUQOSCfg {
	if in == nil {
		return nil
	}
	out := new(CPUQOSCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUSetPolicyCfg) DeepCopyInto(out *CPUSetPolicyCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUSetPolicyCfg.
func (in *CPUSetPolicyCfg) DeepCopy() *CPUSetPolicyCfg {
	if in == nil {
		return nil
	}
	out := new(CPUSetPolicyCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUThrottle) DeepCopyInto(out *CPUThrottle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUThrottle.
func (in *CPUThrottle) DeepCopy() *CPUThrottle {
	if in == nil {
		return nil
	}
	out := new(CPUThrottle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskIOLimitCfg) DeepCopyInto(out *DiskIOLimitCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskIOLimitCfg.
func (in *DiskIOLimitCfg) DeepCopy() *DiskIOLimitCfg {
	if in == nil {
		return nil
	}
	out := new(DiskIOLimitCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskIOQOS) DeepCopyInto(out *DiskIOQOS) {
	*out = *in
	out.DiskIOWeightCfg = in.DiskIOWeightCfg
	out.DiskIOLimitCfg = in.DiskIOLimitCfg
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskIOQOS.
func (in *DiskIOQOS) DeepCopy() *DiskIOQOS {
	if in == nil {
		return nil
	}
	out := new(DiskIOQOS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskIOWeightCfg) DeepCopyInto(out *DiskIOWeightCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskIOWeightCfg.
func (in *DiskIOWeightCfg) DeepCopy() *DiskIOWeightCfg {
	if in == nil {
		return nil
	}
	out := new(DiskIOWeightCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionAction) DeepCopyInto(out *EvictionAction) {
	*out = *in
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionAction.
func (in *EvictionAction) DeepCopy() *EvictionAction {
	if in == nil {
		return nil
	}
	out := new(EvictionAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HtIsolateCfg) DeepCopyInto(out *HtIsolateCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HtIsolateCfg.
func (in *HtIsolateCfg) DeepCopy() *HtIsolateCfg {
	if in == nil {
		return nil
	}
	out := new(HtIsolateCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LowestPriorityNodeCpuLimit) DeepCopyInto(out *LowestPriorityNodeCpuLimit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LowestPriorityNodeCpuLimit.
func (in *LowestPriorityNodeCpuLimit) DeepCopy() *LowestPriorityNodeCpuLimit {
	if in == nil {
		return nil
	}
	out := new(LowestPriorityNodeCpuLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemAsyncReclaim) DeepCopyInto(out *MemAsyncReclaim) {
	*out = *in
	if in.AsyncRatio != nil {
		in, out := &in.AsyncRatio, &out.AsyncRatio
		*out = new(uint64)
		**out = **in
	}
	if in.AsyncDistanceFactor != nil {
		in, out := &in.AsyncDistanceFactor, &out.AsyncDistanceFactor
		*out = new(uint64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemAsyncReclaim.
func (in *MemAsyncReclaim) DeepCopy() *MemAsyncReclaim {
	if in == nil {
		return nil
	}
	out := new(MemAsyncReclaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemWatermark) DeepCopyInto(out *MemWatermark) {
	*out = *in
	if in.WatermarkRatio != nil {
		in, out := &in.WatermarkRatio, &out.WatermarkRatio
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemWatermark.
func (in *MemWatermark) DeepCopy() *MemWatermark {
	if in == nil {
		return nil
	}
	out := new(MemWatermark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryQOSCfg) DeepCopyInto(out *MemoryQOSCfg) {
	*out = *in
	in.MemAsyncReclaim.DeepCopyInto(&out.MemAsyncReclaim)
	in.MemWatermark.DeepCopyInto(&out.MemWatermark)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryQOSCfg.
func (in *MemoryQOSCfg) DeepCopy() *MemoryQOSCfg {
	if in == nil {
		return nil
	}
	out := new(MemoryQOSCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryThrottle) DeepCopyInto(out *MemoryThrottle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryThrottle.
func (in *MemoryThrottle) DeepCopy() *MemoryThrottle {
	if in == nil {
		return nil
	}
	out := new(MemoryThrottle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricRule) DeepCopyInto(out *MetricRule) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Value = in.Value.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricRule.
func (in *MetricRule) DeepCopy() *MetricRule {
	if in == nil {
		return nil
	}
	out := new(MetricRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetIOQOSCfg) DeepCopyInto(out *NetIOQOSCfg) {
	*out = *in
	out.NetLimits = in.NetLimits
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetIOQOSCfg.
func (in *NetIOQOSCfg) DeepCopy() *NetIOQOSCfg {
	if in == nil {
		return nil
	}
	out := new(NetIOQOSCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetLimits) DeepCopyInto(out *NetLimits) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetLimits.
func (in *NetLimits) DeepCopy() *NetLimits {
	if in == nil {
		return nil
	}
	out := new(NetLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalGet) DeepCopyInto(out *NodeLocalGet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalGet.
func (in *NodeLocalGet) DeepCopy() *NodeLocalGet {
	if in == nil {
		return nil
	}
	out := new(NodeLocalGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicy) DeepCopyInto(out *NodeQOSEnsurancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicy.
func (in *NodeQOSEnsurancePolicy) DeepCopy() *NodeQOSEnsurancePolicy {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeQOSEnsurancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicyList) DeepCopyInto(out *NodeQOSEnsurancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeQOSEnsurancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicyList.
func (in *NodeQOSEnsurancePolicyList) DeepCopy() *NodeQOSEnsurancePolicyList {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeQOSEnsurancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicySpec) DeepCopyInto(out *NodeQOSEnsurancePolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.NodeQualityProbe.DeepCopyInto(&out.NodeQualityProbe)
	if in.ObjectiveEnsurances != nil {
		in, out := &in.ObjectiveEnsurances, &out.ObjectiveEnsurances
		*out = make([]QOSEnsurance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicySpec.
func (in *NodeQOSEnsurancePolicySpec) DeepCopy() *NodeQOSEnsurancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQOSEnsurancePolicyStatus) DeepCopyInto(out *NodeQOSEnsurancePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQOSEnsurancePolicyStatus.
func (in *NodeQOSEnsurancePolicyStatus) DeepCopy() *NodeQOSEnsurancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NodeQOSEnsurancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQualityProbe) DeepCopyInto(out *NodeQualityProbe) {
	*out = *in
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(corev1.HTTPGetAction)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeLocalGet != nil {
		in, out := &in.NodeLocalGet, &out.NodeLocalGet
		*out = new(NodeLocalGet)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQualityProbe.
func (in *NodeQualityProbe) DeepCopy() *NodeQualityProbe {
	if in == nil {
		return nil
	}
	out := new(NodeQualityProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OfflineCpuAvoidance) DeepCopyInto(out *OfflineCpuAvoidance) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OfflineCpuAvoidance.
func (in *OfflineCpuAvoidance) DeepCopy() *OfflineCpuAvoidance {
	if in == nil {
		return nil
	}
	out := new(OfflineCpuAvoidance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicy) DeepCopyInto(out *PodQOSEnsurancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicy.
func (in *PodQOSEnsurancePolicy) DeepCopy() *PodQOSEnsurancePolicy {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodQOSEnsurancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicyList) DeepCopyInto(out *PodQOSEnsurancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodQOSEnsurancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicyList.
func (in *PodQOSEnsurancePolicyList) DeepCopy() *PodQOSEnsurancePolicyList {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodQOSEnsurancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicySpec) DeepCopyInto(out *PodQOSEnsurancePolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.QualityProbe.DeepCopyInto(&out.QualityProbe)
	if in.ObjectiveEnsurances != nil {
		in, out := &in.ObjectiveEnsurances, &out.ObjectiveEnsurances
		*out = make([]QOSEnsurance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicySpec.
func (in *PodQOSEnsurancePolicySpec) DeepCopy() *PodQOSEnsurancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodQOSEnsurancePolicyStatus) DeepCopyInto(out *PodQOSEnsurancePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodQOSEnsurancePolicyStatus.
func (in *PodQOSEnsurancePolicyStatus) DeepCopy() *PodQOSEnsurancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PodQOSEnsurancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QOSEnsurance) DeepCopyInto(out *QOSEnsurance) {
	*out = *in
	in.WaterLine.DeepCopyInto(&out.WaterLine)
	out.LowestPriorityNodeCpuLimit = in.LowestPriorityNodeCpuLimit
	if in.LowestPriorityCoreCpuLimit != nil {
		in, out := &in.LowestPriorityCoreCpuLimit, &out.LowestPriorityCoreCpuLimit
		*out = make([]lowestPriorityCoreCpuLimit, len(*in))
		copy(*out, *in)
	}
	if in.LowestPriorityCoreCpuLimitPeriod != nil {
		in, out := &in.LowestPriorityCoreCpuLimitPeriod, &out.LowestPriorityCoreCpuLimitPeriod
		*out = make([]lowestPriorityCoreCpuLimitPeriod, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QOSEnsurance.
func (in *QOSEnsurance) DeepCopy() *QOSEnsurance {
	if in == nil {
		return nil
	}
	out := new(QOSEnsurance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProbe) DeepCopyInto(out *QualityProbe) {
	*out = *in
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(corev1.HTTPGetAction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProbe.
func (in *QualityProbe) DeepCopy() *QualityProbe {
	if in == nil {
		return nil
	}
	out := new(QualityProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDTCfg) DeepCopyInto(out *RDTCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDTCfg.
func (in *RDTCfg) DeepCopy() *RDTCfg {
	if in == nil {
		return nil
	}
	out := new(RDTCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMutation) DeepCopyInto(out *ResourceMutation) {
	*out = *in
	if in.RequestMutations != nil {
		in, out := &in.RequestMutations, &out.RequestMutations
		*out = make([]ResourcetMutation, len(*in))
		copy(*out, *in)
	}
	if in.LimitMutations != nil {
		in, out := &in.LimitMutations, &out.LimitMutations
		*out = make([]ResourcetMutation, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMutation.
func (in *ResourceMutation) DeepCopy() *ResourceMutation {
	if in == nil {
		return nil
	}
	out := new(ResourceMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePriority) DeepCopyInto(out *ResourcePriority) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePriority.
func (in *ResourcePriority) DeepCopy() *ResourcePriority {
	if in == nil {
		return nil
	}
	out := new(ResourcePriority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQOS) DeepCopyInto(out *ResourceQOS) {
	*out = *in
	if in.CPUQOS != nil {
		in, out := &in.CPUQOS, &out.CPUQOS
		*out = new(CPUQOSCfg)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryQOS != nil {
		in, out := &in.MemoryQOS, &out.MemoryQOS
		*out = new(MemoryQOSCfg)
		(*in).DeepCopyInto(*out)
	}
	if in.NetIOQOS != nil {
		in, out := &in.NetIOQOS, &out.NetIOQOS
		*out = new(NetIOQOSCfg)
		**out = **in
	}
	if in.DiskIOQOS != nil {
		in, out := &in.DiskIOQOS, &out.DiskIOQOS
		*out = new(DiskIOQOS)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQOS.
func (in *ResourceQOS) DeepCopy() *ResourceQOS {
	if in == nil {
		return nil
	}
	out := new(ResourceQOS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcetMutation) DeepCopyInto(out *ResourcetMutation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcetMutation.
func (in *ResourcetMutation) DeepCopy() *ResourcetMutation {
	if in == nil {
		return nil
	}
	out := new(ResourcetMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicy) DeepCopyInto(out *ServicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicy.
func (in *ServicePolicy) DeepCopy() *ServicePolicy {
	if in == nil {
		return nil
	}
	out := new(ServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServicePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicyList) DeepCopyInto(out *ServicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServicePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicyList.
func (in *ServicePolicyList) DeepCopy() *ServicePolicyList {
	if in == nil {
		return nil
	}
	out := new(ServicePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServicePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicySpec) DeepCopyInto(out *ServicePolicySpec) {
	*out = *in
	out.ResourcePriority = in.ResourcePriority
	out.AvoidanceStrategy = in.AvoidanceStrategy
	in.ResourceMutation.DeepCopyInto(&out.ResourceMutation)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicySpec.
func (in *ServicePolicySpec) DeepCopy() *ServicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ServicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicyStatus) DeepCopyInto(out *ServicePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicyStatus.
func (in *ServicePolicyStatus) DeepCopy() *ServicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ServicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceQOS) DeepCopyInto(out *ServiceQOS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceQOS.
func (in *ServiceQOS) DeepCopy() *ServiceQOS {
	if in == nil {
		return nil
	}
	out := new(ServiceQOS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceQOS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceQOSEnsurancePolicyStatus) DeepCopyInto(out *ServiceQOSEnsurancePolicyStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceQOSEnsurancePolicyStatus.
func (in *ServiceQOSEnsurancePolicyStatus) DeepCopy() *ServiceQOSEnsurancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceQOSEnsurancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceQOSList) DeepCopyInto(out *ServiceQOSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceQOS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceQOSList.
func (in *ServiceQOSList) DeepCopy() *ServiceQOSList {
	if in == nil {
		return nil
	}
	out := new(ServiceQOSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceQOSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceQOSSpec) DeepCopyInto(out *ServiceQOSSpec) {
	*out = *in
	if in.QOSClassSelectors != nil {
		in, out := &in.QOSClassSelectors, &out.QOSClassSelectors
		*out = make([]corev1.PodQOSClass, len(*in))
		copy(*out, *in)
	}
	if in.PriorityClassSelectors != nil {
		in, out := &in.PriorityClassSelectors, &out.PriorityClassSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceSelectors != nil {
		in, out := &in.ResourceSelectors, &out.ResourceSelectors
		*out = make([]analysisv1alpha1.ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceQOS.DeepCopyInto(&out.ResourceQOS)
	if in.AllowedNodeQOSActions != nil {
		in, out := &in.AllowedNodeQOSActions, &out.AllowedNodeQOSActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceQOSSpec.
func (in *ServiceQOSSpec) DeepCopy() *ServiceQOSSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceQOSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottleAction) DeepCopyInto(out *ThrottleAction) {
	*out = *in
	out.CPUThrottle = in.CPUThrottle
	out.MemoryThrottle = in.MemoryThrottle
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottleAction.
func (in *ThrottleAction) DeepCopy() *ThrottleAction {
	if in == nil {
		return nil
	}
	out := new(ThrottleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaterLine) DeepCopyInto(out *WaterLine) {
	*out = *in
	if in.MetricRule != nil {
		in, out := &in.MetricRule, &out.MetricRule
		*out = new(MetricRule)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaterLine.
func (in *WaterLine) DeepCopy() *WaterLine {
	if in == nil {
		return nil
	}
	out := new(WaterLine)
	in.DeepCopyInto(out)
	return out
}
